apiVersion: v1
kind: ConfigMap
metadata:
  name: artemis-broker-config
data:
  broker.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <broker xmlns="http://activemq.apache.org/schema/artemis/broker">
      <name>artemis-broker</name>
      <jmx-management-enabled>true</jmx-management-enabled>
      <acceptors>
        <acceptor name="amqp">tcp://0.0.0.0:61616?protocols=AMQP</acceptor>
        <acceptor name="http">tcp://0.0.0.0:8161?httpEnabled=true</acceptor>
      </acceptors>
      <destinationInterceptors>
        <mirroredQueue copyMessage = "true" postfix=".qmirror" prefix=""/>
      </destinationInterceptors>
      <address-settings>
        <address-setting match="#">
          <auto-create-queues>true</auto-create-queues>
          <auto-create-addresses>true</auto-create-addresses>
          <default-queue-routing-type>ANYCAST</default-queue-routing-type>
          <default-address-routing-type>ANYCAST</default-address-routing-type>
        </address-setting>
      </address-settings>
    </broker>
