apiVersion: v1
kind: Service
metadata:
  name: artemis
spec:
  type: LoadBalancer
  selector:
    app: artemis
  ports:
    - name: console
      port: 8161
      targetPort: 8161
    - name: amqp
      port: 61616
      targetPort: 61616
